### ISSUE TITLE
Unclear: how to resolve references?

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#137]
What I am trying to do:
* hook into a predefined fork for declarations: reduce the enum literals to constants.
* hook into a predefined fork for expressions: reduce enum literal ref to constant ref

![screenshot 2019-02-03 at 19 25 23](https://user-images.githubusercontent.com/592330/52180665-7bd60e80-27e9-11e9-8797-4f3d8d88765a.png)

But I get an error: 

    Failed to resolve CallInContext{call=de.q60.mps.shadowmodels.examples.expext.transformations.ExtDeclarations.t3(°green), context=empty/$shadowRepository.de.q60.mps.shadowmodels.repository.transformations.ShadowRepository.$Repository(°de.q60.mps.shadowmodels.runtime.smodel.SRepositoryAsNode@1491ff71)/de.q60.mps.shadowmodels.examples.expressions.transformations.Declarations.forkDecl[de.q60.mps.shadowmodels.examples.expressions.transformations.Declarations.forkDecl/rewriter].de.q60.mps.shadowmodels.examples.expressions.transformations.Declarations.decl(°temp)}

I had tried with labels as well. DIdn't work either; same error.

![screenshot 2019-02-03 at 19 27 49](https://user-images.githubusercontent.com/592330/52180697-d7a09780-27e9-11e9-9f23-2f12a5b01d40.png)

**Comment by markusvoelter** [comment]
pushed on ```markus-expressions```

**Comment by slisson** [comment]
Fixed and pushed it to your branch. Main problem was, that every IDeclaration was in it's own fork. I put the whole program in one fork.

**Comment by markusvoelter** [comment]
Hmmm. Doesn't this contradict the performance conisderations we talked about last week?

**Comment by slisson** [comment]
One reason to use forks is the reference resolution. Inside a fork it's easier, because we know what is part of the fork. If you put everything into its fork, then you have again the problem that you need to know how to resolve the reference (by adding fork dependencies).

**Comment by markusvoelter** [comment]
I understand.

But what about the performance? You said, "putting everything into a big fork makes things slow".

**Comment by slisson** [comment]
I'm currently working on the performance. They shouldn't be so small that they are useless. A model or root node is a reasonable root for a fork. That's a size they should be able to handle (in the future).
