### ISSUE TITLE
Avoid replacing root nodes in the shadow repository

### ISSUE THREAD

**Issue by slisson** [slisson/shadowmodels#138]
If there is a change in the contributions to the root node, the identity changes and a new root node is created. This is annoying because you have to reopen it from the project view.

**Comment by arimer** [comment]
Currenlty any change in any root of the input model triggers the creation of a new root node. 

In this state it is not possible to have two windows open next to each other (one of the orginal input root node and the transformed output root node) and edit the input model. 

If you do so each chage results in an empty editor telling you: 

<img width="319" alt="grafik" src="https://user-images.githubusercontent.com/16648247/52218654-61f50400-289b-11e9-8126-1e475530fb8f.png">
