### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#154]
Branch: markus-expressions

Run the Explode intention on this node:

    http://127.0.0.1:63320/node?ref=r%3A856330db-0c77-4408-8b12-f8dcc36a4605%28de.q60.mps.shadowmodels.examples.input.altexpression%29%2F4320583889640217190&project=mps-extensions

This multiplies the declarations in the program by a factor of 10. Once this is done, every subsequent edit operation in the program blocks for aroudn two seconds.

**Comment by slisson** [comment]
#141
