### ISSUE TITLE
Rules for child->parent relation

### ISSUE THREAD

**Issue by slisson** [slisson/shadowmodels#32]
Currently, all relations are unidirectional. While for references this is also the case in MPS, for parent-child relations it's only possible to navigate to a child, but not to a parent.

Most parent rules can be derived from inverting the often simple expressions used to navigate from the parent to the child. What makes this problem non trivial is that transformation rules usually know nothing about their context in that they are used, because they can be used at multiple locations.

As an alternative it could be done at runtime by simply remembering which rule called the rule that produced the child. This works in cases where the possible parent rules can be computed eagerly.

**Comment by markusvoelter** [comment]
An approach that can serve as an alternative is to explicitly mark some rules as specific to a particular call site. This makes the rule non-reusable, but makes finding the parent trivial. While this should not be the general/only strategy, it is certainly acceptable for some cases. So one could allow to mark a rule as "can only be used in this context/called from this location".  As a side benefit, this approach could also be used for references where the "way back" is necessary.

**Comment by slisson** [comment]
Solves #18

**Comment by slisson** [comment]
Obsolete. See #38
