### ISSUE TITLE
Transforming Lists to Trees

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#37]
A common use case is the transformation of list (in the source) to a tree in the target (and vice versa); specialized support in the language is justifiable. An example can be found as part of the Alt-desugaring use case:

    http://127.0.0.1:63320/node?ref=r%3A49e489bb-f00f-4c40-a675-08c681da1ac3%28shadowmodels.usecase.expr.transformations%29%2F2583804470398796151

Right now, this cannot be expressed. A solution should take into account that, if only one element in the list is changed or added or removed, the transformation is NOT executed for the whole list.

**Comment by slisson** [comment]
Possible solution is something similar to the fold operation for sequences in MPS:

```
Fold implements INodeSpec
  inputList: Expression
  seed: INodeSpec
  body: INodeSpec
```

```
Unfold implements INodeSpec
  input: Expression
  tail: Expression
  head: INodeSpec
```

```
altToIf [alt: AltExpr] ->
  foldR alt.cases, null, IfExpr {
    cond: it.cond
    thenPart: it.val
    elsePart: s
  }
```

```
ifToAlt [ifExpr: IfExpr] ->
  AltExpr {
    cases: unfold ifExpr, ifExpr.elsePart, AltCase {
      cond: it.cond
      val: it.thenPart
    }
  }
```
