### ISSUE TITLE
copy macro does not work for lists

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#72]
<img width="333" alt="screen shot 2018-12-17 at 07 51 47" src="https://user-images.githubusercontent.com/592330/50071037-b4397300-01d0-11e9-8c7e-c558c37b71d9.png">

It is syntactically ok, but then I get a compiler error:

de/q60/mps/shadowmodels/examples/expressions/transformations/Repo.java : The method copy(SNode) in the type CopySNodeToTransformationResult is not applicable for the arguments (List<SNode>) (line: 167)

**Comment by slisson** [comment]
You can use a map macro and do the copy in a separate rule, what is usually prefered anyway.

**Comment by markusvoelter** [comment]
Yes, this is what I had figured out as well, but 

1) this is nonetheless a lot of boilerplate one has to write to do "nothing", and
2) at the very least, copy with a list should then be marked as an error
