### ISSUE TITLE
An automatic mechanism for references?

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#73]
I have the typical desugaring transformation. For a function, the arguments survive unchanged. So I use copy to duplicate them into the target model. However, because there identity changes, I now have to write a desugaring rule for all my ArgRefs to point to the new identity.

I wonder if this could be automated: if instead of copy there were a "clone" or something which implies tht logically, the identity remains unchanged, then the references to it could perhaps automatically be updated?

**Comment by slisson** [comment]
Documentation for `copy` required.

**Comment by slisson** [comment]
#88

**Comment by slisson** [comment]
Reference resolution improved a lot with the introduction of subgraphs.

**Comment by markusvoelter** [comment]
I have a Program that declares Enums. Those contain EnumLits. 

![screenshot 2019-02-03 at 19 10 44](https://user-images.githubusercontent.com/592330/52180507-6fe94d00-27e7-11e9-9484-04a952f46d05.png)

Then I have EnumRef expressions that refenrece it:

![screenshot 2019-02-03 at 19 11 19](https://user-images.githubusercontent.com/592330/52180514-842d4a00-27e7-11e9-88b2-b56c2a5e6d76.png)

I have a fork/reduction fo the value of a constant. Which is why the EnumRef "green" in the val wil be copied. I also copy the declaration, because I copy each declaration (and call the fork). However, in the target model, the references still point to the original model.
