### ISSUE TITLE
Replace one node with many?

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#76]
Relating to #75 : Is this even the right way to replace one node (Enum) with many (a constant per literal)?

**Comment by slisson** [comment]
Yes, it is.

**Comment by slisson** [comment]
Typesystem shows an error and only the first element appears in the output.

**Comment by slisson** [comment]
Branch markus-shadow
URL http://127.0.0.1:63320/node?ref=r%3A49e489bb-f00f-4c40-a675-08c681da1ac3%28de.q60.mps.shadowmodels.examples.expressions.transformations%29%2F549502488714645136&project=mps-extensions
