### ISSUE TITLE
References are broken when using the CopyMacro

### ISSUE THREAD

**Issue by slisson** [slisson/shadowmodels#90]
References to nodes that are not part of the copied sub tree are broken.

**Comment by slisson** [comment]
Related to #46

**Comment by markusvoelter** [comment]
Does this also address #73 ?

**Comment by slisson** [comment]
No, with this fix references will remain unchanged. In #73, the reference target is transformed and references need to point to the output node. This still doesn't happen.

**Comment by markusvoelter** [comment]
Ok, then we'll leave #73 open for now.

**Comment by slisson** [comment]
Reopened because some references now point to transient nodes that are not part of the repository.

**Comment by fvollmer** [comment]
Here a simple example I have created to show this problem with the copy macro:
https://github.com/fvollmer/ShadowModelPlayground
The example itself is pretty boring, but maybe you find it is useful.

![mps](https://user-images.githubusercontent.com/16699443/50641373-01a33780-0f68-11e9-9368-777d50bf9823.png)

You can press F5 a lot and the automatic resolver can get around it.
![mps2](https://user-images.githubusercontent.com/16699443/50642745-6eb8cc00-0f6c-11e9-8bf0-e20149ea1a51.png)
![mps3](https://user-images.githubusercontent.com/16699443/50642732-6365a080-0f6c-11e9-8e1b-5d9dfdf57d49.png)
