### ISSUE TITLE
Documentation: Explain desugaring use case

### ISSUE THREAD

**Issue by slisson** [slisson/shadowmodels#97]
This use cases copies most of the input.
It uses the pattern of a transformation that recursively invokes itself on the child nodes.
Explain why this is required and how and why this is different to term replacement system as the MPS generator.

**Comment by slisson** [comment]
Maybe we need abstractions for this use case that makes it easier to implement?

**Comment by markusvoelter** [comment]
Yes :-)

For example, simple, declarative "replacemnts": EnumLitRef -> COnstantRef given as part of the transformation from EnumDecl to Constant

**Comment by slisson** [comment]
Doesn't need more documentation or reusable abstractions. It's a symptom of the wrong approach. Not everything is bad in term rewriting systems. Just need to find a way to mix both approaches to get the best of both worlds.

**Comment by slisson** [comment]
Even ATL knowns that this use case is special. They have two different modes for module execution: https://wiki.eclipse.org/ATL/User_Guide_-_Overview_of_the_ATL_Language#Module_execution_modes

**Comment by slisson** [comment]
Obsolete. Forks/subgraph allow MPS style transformations.
