### ISSUE TITLE
Documentation: Transformation stages

### ISSUE THREAD

**Issue by slisson** [slisson/shadowmodels#98]
In MPS transient models are isolated more strictly. Shadow model transformations happen on the granularity of nodes. You can have a separate transformation paths per node. This allows very powerful and complex transformations, but is hard to understand.
This is especially true for handling references. Users also like to use the copy macro and are surprised when references are broken. Maybe make it non-recursive by default to encourage users to use it in a correct way.

**Comment by slisson** [comment]
Maybe related to #69. The debugger should help to understand why a reference is broken and how to fix it.

**Comment by slisson** [comment]
#95

**Comment by slisson** [comment]
If it is hard to understand, we don't need more documentation. The solution may just be crap. Solved by the introduction of subgraphs. Still needs documentation, but a different one.

**Comment by markusvoelter** [comment]
.. might also be solved be fixpoints!
